name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run deploy
      env:
        VITE_BASE_URL: ${{ secrets.BASE_URL }}
        VITE_MEDIA_URL: ${{ secrets.MEDIA_URL }}
        VITE_IMAGE_URL: ${{ secrets.IMAGE_URL }}
        VITE_BASE_URL_VERSION: ${{ secrets.BASE_URL_VERSION }}
        VITE_GA: ${{ secrets.GA }}
        VITE_GMT: ${{ secrets.GMT }}
        VITE_TOKEN: ${{ secrets.TOKEN }}
        VITE_VIDEO_ID: ${{ secrets.VIDEO_ID }}
        VITE_PLAYLIST_ID: ${{ secrets.PLAYLIST_ID }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build