name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Create env file
      working-directory: .
      run: |
        echo '${{ secrets.ENV_FILE }}' > .env

    - name: Build
      run: |
        cat .env
        npm ci
        npm run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        folder: build